### ISSUE TITLE
White square

### ISSUE THREAD

**Issue by radioactive68** [jamiebicknell/Thumb#11]
White square

cache browser - clear
cache folder - clear
error log - 0
Locally - works

![screenshot_1](https://user-images.githubusercontent.com/2676046/27688881-d888ea98-5ce4-11e7-8404-31e4277e8a50.png)

**Comment by jamiebicknell** [comment]
Can you attach one of the cache files here please?

**Comment by radioactive68** [comment]
[65500d32c0b6c0fffb1265e5de587f26.img.txt](https://github.com/jamiebicknell/Thumb/files/1111540/65500d32c0b6c0fffb1265e5de587f26.img.txt)

**Comment by jamiebicknell** [comment]
It looks like the problem lies in the image generation part. Can you check a few things:

1. That error logging is enabled via PHP.ini so that errors are actually written to the log
2. What version of PHP and GD you are running on the server (use phpinfo() to display this data)

**Comment by jamiebicknell** [comment]
Can you try removing lines 267-280 (the header bits)? That may expose some errors that might help me to get to the root of this issue.

**Comment by jamiebicknell** [comment]
Ok, I downloaded one of the output files on your site and viewed the file in a text editor and the error is as follows:

> **Warning**:  strtotime() [function.strtotime]: It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Moscow' for 'MSK/3.0/no DST' instead in **/var/www/up042654/data/www/icase.su/wp-content/themes/iphone/thumb.php** on line **275**

This would be due to the server configuration. To fix this issue please set the timezone in the `PHP.ini` file or add the following to the top of the `thumb.php` file:

```php
date_default_timezone_set('Europe/Moscow');
```
