### ISSUE TITLE
Having the can't display this image as it has errors problem

### ISSUE THREAD

**Issue by popencer** [jamiebicknell/Thumb#13]
Having the can't display this image as it has errors problem
https://muskokaradio.com/thumbing.php?src=./media/huntsville/healthy-huntsville-pledge.jpg&size=400x300

Permissions are write-able (it adds an index.html file to the directory)
No errors in the php log?

**Comment by jamiebicknell** [comment]
It doesn't appear that the file exists on your server, perhaps the path is wrong?
