### ISSUE TITLE
Is it possible to show external url photo?

### ISSUE THREAD

**Issue by ohokbd** [jamiebicknell/Thumb#15]
Please kindly add a feature for the external photo view, so that the white level domain can be set on the script to allow the view,

**Comment by jamiebicknell** [comment]
Hello,

Unfortunately due to security concerns this isn't a feature that I will adding to the script, even with a white list domain.

Please feel free to fork and update it yourself if you wish.

**Comment by ohokbd** [comment]
Thank you for your reply.  Really this is an awesome script.  

Also May I know if there will any other updates coming for this script near future ?

**Comment by jamiebicknell** [comment]
I think the script does everything it was intended it to, I didn't want to bloat it out with features that may make it run slower, but I'm open to suggestions if you have any further ideas on functionality.

The only one that if a definite no would be the external URL facility.

**Comment by ohokbd** [comment]
Some suggestions: 

1. A lite version of the script (cache, src, size) functions only.
2. Gif Image does not animate while calling through the thumb is it possible to animate (for gif image only)

Thank you.
