### ISSUE TITLE
Unable to create thumb of gif file type

### ISSUE THREAD

**Issue by flik** [jamiebicknell/Thumb#4]
This error message is coming : cannot be displayed because it contains errors.

**Comment by jamiebicknell** [comment]
I can create thumbs of GIFs without issue here, so I'm thinking this is a different issue.

Could you upload the GIF somewhere in it's original form and post the URL please? Also, try checking your PHP error log to find out exactly what the error is, and please paste this in here too.

**Comment by flik** [comment]
I was trying this file: http://fc07.deviantart.net/fs71/f/2012/212/5/2/tumblr_background___loki___avengers_edition_by_miratheracusia-d57swys.gif

You can download and then try for thumbnail

**Comment by jamiebicknell** [comment]
I have no issue creating a thumb of this image.

One thing to look out for is the file permissions, make sure PHP has the ability to read the file. When I download from Chrome, it sets read access to no access for all users but me, so this could be what's happening.

**Comment by flik** [comment]
Now, I have given all permissions but still giving me this error...
The image “http://localhost/Thumb/thumb.php?src=./images/picgif.gif&size=400x300” cannot be displayed because it contains errors.

Do you have any online demo page ? I will try to upload for you to test on my server.

**Comment by flik** [comment]
ok. Now It is working.

**Comment by flik** [comment]
thanks

**Comment by flik** [comment]
It was generated in crome but not in firefox.
http://localhost/Thumb/thumb.php?src=./images/picgif.gif&size=400x300
same url but work in crome and It is not working in firefox

**Comment by jamiebicknell** [comment]
Try this: remove all files within the cache directory and reload.

Also, clear browser cache if you can.

If still not working then look at your PHP error logs as this will show you exactly what the error is.

**Comment by flik** [comment]
Ok. working with removed cache files by cache folder. thanks :)
