### ISSUE TITLE
Set image quality

### ISSUE THREAD

**Issue by koertho** [jamiebicknell/Thumb#8]
Sometimes the thumbsnail generated with this library have a bigger file size then the original files, even when they have a bigger resolution. The problem is, that the generated images (jpg) have always 100% image quality. It would be great to set the file quality in the parameter or the library should use the quality of the original image.

**Comment by jamiebicknell** [comment]
I've never been keen on having a query string option that only applies one particular file format, but I do agree that the quality should be able to be customised somewhere. Instead I think it's best if the quality was configured as a constant and same for each instance.

View commit here: 0930eea51bc7b9b6dc9a874ac36eb9b2592b102d

**Comment by koertho** [comment]
That's perfect. Thank you!

**Comment by jamiebicknell** [comment]
The constant is my preference as I feel the quality wouldn't change on a per image basis, but more or a per install/instance basis. If you do use you're query string version, don't forgot to also add the quality option to the `$file_hash` variable.
